name: Fetch latest FAA data

on:
  workflow_dispatch:
  schedule:
    # Data is updated at "11:30pm central" - which I take to be 4:30am or
    # 5:30am UTC depending on daylight savings. So this runs at 6am UTC.
    - cron: '0 6 * * *'

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch and unzip
      run: |        
        rm -rf ReleasableAircraft
        wget https://registry.faa.gov/database/ReleasableAircraft.zip
        unzip ReleasableAircraft.zip
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
